/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CaseDocument {
  'id' : string,
  'documentType' : DocumentType,
  'user' : Principal,
  'fileName' : string,
  'fileSize' : bigint,
  'fileContent' : ExternalBlob,
  'submissionId' : string,
  'uploadTime' : Time,
}
export interface CaseSubmission {
  'id' : string,
  'status' : SubmissionStatus,
  'paymentMethod' : PaymentMethod,
  'user' : Principal,
  'timestamp' : Time,
  'details' : string,
}
export type DocumentType = { 'affidavit' : null } |
  { 'other' : string } |
  { 'evidence' : null } |
  { 'courtOrder' : null };
export interface DraftMotion {
  'id' : string,
  'content' : string,
  'motionType' : string,
  'user' : Principal,
  'createdTime' : Time,
  'submissionId' : string,
}
export type ExternalBlob = Uint8Array;
export interface NewCaseData {
  'paymentMethod' : PaymentMethod,
  'details' : string,
}
export type PaymentMethod = { 'card' : null } |
  { 'cashapp' : null } |
  { 'inPersonCash' : null } |
  { 'paypal' : null };
export interface PaymentReference {
  'referenceType' : ReferenceType,
  'submissionId' : string,
  'referenceValue' : string,
}
export interface ReferenceLibraryEntry {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdBy' : Principal,
  'author' : string,
  'dateAdded' : Time,
}
export type ReferenceType = { 'paypalTransactionId' : null } |
  { 'cashappUsername' : null } |
  { 'storePaymentCode' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubmissionStatus = { 'paid' : null } |
  { 'completed' : null } |
  { 'pendingPayment' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReferenceEntry' : ActorMethod<[string, string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCase' : ActorMethod<[NewCaseData], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createDraftMotion' : ActorMethod<[string, string, string], string>,
  'getAllSubmissions' : ActorMethod<[], Array<CaseSubmission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[string], [] | [CaseDocument]>,
  'getDocumentsBySubmission' : ActorMethod<[string], Array<CaseDocument>>,
  'getDraftMotionsBySubmission' : ActorMethod<[string], Array<DraftMotion>>,
  'getMySubmissions' : ActorMethod<[], Array<CaseSubmission>>,
  'getPaymentReference' : ActorMethod<[string], [] | [PaymentReference]>,
  'getReferenceEntry' : ActorMethod<[string], [] | [ReferenceLibraryEntry]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubmission' : ActorMethod<[string], [] | [CaseSubmission]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchReferenceEntries' : ActorMethod<
    [string],
    Array<ReferenceLibraryEntry>
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitPaymentReference' : ActorMethod<
    [string, ReferenceType, string],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSubmissionStatusAdmin' : ActorMethod<
    [string, SubmissionStatus],
    undefined
  >,
  'uploadDocument' : ActorMethod<
    [string, DocumentType, string, bigint, ExternalBlob],
    string
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];