/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'card' : IDL.Null,
  'cashapp' : IDL.Null,
  'inPersonCash' : IDL.Null,
  'paypal' : IDL.Null,
});
export const NewCaseData = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'details' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const SubmissionStatus = IDL.Variant({
  'paid' : IDL.Null,
  'completed' : IDL.Null,
  'pendingPayment' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const CaseSubmission = IDL.Record({
  'id' : IDL.Text,
  'status' : SubmissionStatus,
  'paymentMethod' : PaymentMethod,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const DocumentType = IDL.Variant({
  'affidavit' : IDL.Null,
  'other' : IDL.Text,
  'evidence' : IDL.Null,
  'courtOrder' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CaseDocument = IDL.Record({
  'id' : IDL.Text,
  'documentType' : DocumentType,
  'user' : IDL.Principal,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileContent' : ExternalBlob,
  'submissionId' : IDL.Text,
  'uploadTime' : Time,
});
export const DraftMotion = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'motionType' : IDL.Text,
  'user' : IDL.Principal,
  'createdTime' : Time,
  'submissionId' : IDL.Text,
});
export const ReferenceType = IDL.Variant({
  'paypalTransactionId' : IDL.Null,
  'cashappUsername' : IDL.Null,
  'storePaymentCode' : IDL.Null,
});
export const PaymentReference = IDL.Record({
  'referenceType' : ReferenceType,
  'submissionId' : IDL.Text,
  'referenceValue' : IDL.Text,
});
export const ReferenceLibraryEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdBy' : IDL.Principal,
  'author' : IDL.Text,
  'dateAdded' : Time,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReferenceEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCase' : IDL.Func([NewCaseData], [IDL.Text], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createDraftMotion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(CaseSubmission)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [IDL.Opt(CaseDocument)], ['query']),
  'getDocumentsBySubmission' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CaseDocument)],
      ['query'],
    ),
  'getDraftMotionsBySubmission' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DraftMotion)],
      ['query'],
    ),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(CaseSubmission)], ['query']),
  'getPaymentReference' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentReference)],
      ['query'],
    ),
  'getReferenceEntry' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ReferenceLibraryEntry)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubmission' : IDL.Func([IDL.Text], [IDL.Opt(CaseSubmission)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchReferenceEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ReferenceLibraryEntry)],
      ['query'],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitPaymentReference' : IDL.Func(
      [IDL.Text, ReferenceType, IDL.Text],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSubmissionStatusAdmin' : IDL.Func(
      [IDL.Text, SubmissionStatus],
      [],
      [],
    ),
  'uploadDocument' : IDL.Func(
      [IDL.Text, DocumentType, IDL.Text, IDL.Nat, ExternalBlob],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'card' : IDL.Null,
    'cashapp' : IDL.Null,
    'inPersonCash' : IDL.Null,
    'paypal' : IDL.Null,
  });
  const NewCaseData = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'details' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const SubmissionStatus = IDL.Variant({
    'paid' : IDL.Null,
    'completed' : IDL.Null,
    'pendingPayment' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const CaseSubmission = IDL.Record({
    'id' : IDL.Text,
    'status' : SubmissionStatus,
    'paymentMethod' : PaymentMethod,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DocumentType = IDL.Variant({
    'affidavit' : IDL.Null,
    'other' : IDL.Text,
    'evidence' : IDL.Null,
    'courtOrder' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CaseDocument = IDL.Record({
    'id' : IDL.Text,
    'documentType' : DocumentType,
    'user' : IDL.Principal,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileContent' : ExternalBlob,
    'submissionId' : IDL.Text,
    'uploadTime' : Time,
  });
  const DraftMotion = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'motionType' : IDL.Text,
    'user' : IDL.Principal,
    'createdTime' : Time,
    'submissionId' : IDL.Text,
  });
  const ReferenceType = IDL.Variant({
    'paypalTransactionId' : IDL.Null,
    'cashappUsername' : IDL.Null,
    'storePaymentCode' : IDL.Null,
  });
  const PaymentReference = IDL.Record({
    'referenceType' : ReferenceType,
    'submissionId' : IDL.Text,
    'referenceValue' : IDL.Text,
  });
  const ReferenceLibraryEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdBy' : IDL.Principal,
    'author' : IDL.Text,
    'dateAdded' : Time,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReferenceEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCase' : IDL.Func([NewCaseData], [IDL.Text], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createDraftMotion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(CaseSubmission)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([IDL.Text], [IDL.Opt(CaseDocument)], ['query']),
    'getDocumentsBySubmission' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CaseDocument)],
        ['query'],
      ),
    'getDraftMotionsBySubmission' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DraftMotion)],
        ['query'],
      ),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(CaseSubmission)], ['query']),
    'getPaymentReference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentReference)],
        ['query'],
      ),
    'getReferenceEntry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReferenceLibraryEntry)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubmission' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CaseSubmission)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchReferenceEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReferenceLibraryEntry)],
        ['query'],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitPaymentReference' : IDL.Func(
        [IDL.Text, ReferenceType, IDL.Text],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSubmissionStatusAdmin' : IDL.Func(
        [IDL.Text, SubmissionStatus],
        [],
        [],
      ),
    'uploadDocument' : IDL.Func(
        [IDL.Text, DocumentType, IDL.Text, IDL.Nat, ExternalBlob],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };