/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type DocumentType = {
    __kind__: "affidavit";
    affidavit: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "evidence";
    evidence: null;
} | {
    __kind__: "courtOrder";
    courtOrder: null;
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface ReferenceLibraryEntry {
    id: string;
    title: string;
    content: string;
    createdBy: Principal;
    author: string;
    dateAdded: Time;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PaymentReference {
    referenceType: ReferenceType;
    submissionId: string;
    referenceValue: string;
}
export interface CaseDocument {
    id: string;
    documentType: DocumentType;
    user: Principal;
    fileName: string;
    fileSize: bigint;
    fileContent: ExternalBlob;
    submissionId: string;
    uploadTime: Time;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface CaseSubmission {
    id: string;
    status: SubmissionStatus;
    paymentMethod: PaymentMethod;
    user: Principal;
    timestamp: Time;
    details: string;
}
export interface DraftMotion {
    id: string;
    content: string;
    motionType: string;
    user: Principal;
    createdTime: Time;
    submissionId: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface NewCaseData {
    paymentMethod: PaymentMethod;
    details: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export enum PaymentMethod {
    card = "card",
    cashapp = "cashapp",
    inPersonCash = "inPersonCash",
    paypal = "paypal"
}
export enum ReferenceType {
    paypalTransactionId = "paypalTransactionId",
    cashappUsername = "cashappUsername",
    storePaymentCode = "storePaymentCode"
}
export enum SubmissionStatus {
    paid = "paid",
    completed = "completed",
    pendingPayment = "pendingPayment",
    processing = "processing",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addReferenceEntry(title: string, content: string, author: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCase(newCaseData: NewCaseData): Promise<string>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createDraftMotion(submissionId: string, motionType: string, content: string): Promise<string>;
    getAllSubmissions(): Promise<Array<CaseSubmission>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDocument(documentId: string): Promise<CaseDocument | null>;
    getDocumentsBySubmission(submissionId: string): Promise<Array<CaseDocument>>;
    getDraftMotionsBySubmission(submissionId: string): Promise<Array<DraftMotion>>;
    getMySubmissions(): Promise<Array<CaseSubmission>>;
    getPaymentReference(submissionId: string): Promise<PaymentReference | null>;
    getReferenceEntry(entryId: string): Promise<ReferenceLibraryEntry | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubmission(submissionId: string): Promise<CaseSubmission | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchReferenceEntries(searchText: string): Promise<Array<ReferenceLibraryEntry>>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitPaymentReference(submissionId: string, referenceType: ReferenceType, referenceValue: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateSubmissionStatusAdmin(submissionId: string, newStatus: SubmissionStatus): Promise<void>;
    uploadDocument(submissionId: string, documentType: DocumentType, fileName: string, fileSize: bigint, fileContent: ExternalBlob): Promise<string>;
}
import type { CaseDocument as _CaseDocument, CaseSubmission as _CaseSubmission, DocumentType as _DocumentType, ExternalBlob as _ExternalBlob, NewCaseData as _NewCaseData, PaymentMethod as _PaymentMethod, PaymentReference as _PaymentReference, ReferenceLibraryEntry as _ReferenceLibraryEntry, ReferenceType as _ReferenceType, StripeSessionStatus as _StripeSessionStatus, SubmissionStatus as _SubmissionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addReferenceEntry(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReferenceEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReferenceEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCase(arg0: NewCaseData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCase(to_candid_NewCaseData_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCase(to_candid_NewCaseData_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createDraftMotion(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDraftMotion(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDraftMotion(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<CaseSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: string): Promise<CaseDocument | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentsBySubmission(arg0: string): Promise<Array<CaseDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentsBySubmission(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentsBySubmission(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDraftMotionsBySubmission(arg0: string): Promise<Array<DraftMotion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDraftMotionsBySubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDraftMotionsBySubmission(arg0);
            return result;
        }
    }
    async getMySubmissions(): Promise<Array<CaseSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmissions();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmissions();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentReference(arg0: string): Promise<PaymentReference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentReference(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentReference(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferenceEntry(arg0: string): Promise<ReferenceLibraryEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferenceEntry(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferenceEntry(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmission(arg0: string): Promise<CaseSubmission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmission(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmission(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchReferenceEntries(arg0: string): Promise<Array<ReferenceLibraryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchReferenceEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchReferenceEntries(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitPaymentReference(arg0: string, arg1: ReferenceType, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPaymentReference(arg0, to_candid_ReferenceType_n42(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPaymentReference(arg0, to_candid_ReferenceType_n42(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateSubmissionStatusAdmin(arg0: string, arg1: SubmissionStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmissionStatusAdmin(arg0, to_candid_SubmissionStatus_n44(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmissionStatusAdmin(arg0, to_candid_SubmissionStatus_n44(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadDocument(arg0: string, arg1: DocumentType, arg2: string, arg3: bigint, arg4: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(arg0, to_candid_DocumentType_n46(this._uploadFile, this._downloadFile, arg1), arg2, arg3, await to_candid_ExternalBlob_n48(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(arg0, to_candid_DocumentType_n46(this._uploadFile, this._downloadFile, arg1), arg2, arg3, await to_candid_ExternalBlob_n48(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
async function from_candid_CaseDocument_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseDocument): Promise<CaseDocument> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_CaseSubmission_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaseSubmission): CaseSubmission {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_DocumentType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PaymentMethod_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentReference_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentReference): PaymentReference {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ReferenceType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReferenceType): ReferenceType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CaseDocument]): Promise<CaseDocument | null> {
    return value.length === 0 ? null : await from_candid_CaseDocument_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentReference]): PaymentReference | null {
    return value.length === 0 ? null : from_candid_PaymentReference_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReferenceLibraryEntry]): ReferenceLibraryEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CaseSubmission]): CaseSubmission | null {
    return value.length === 0 ? null : from_candid_CaseSubmission_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _SubmissionStatus;
    paymentMethod: _PaymentMethod;
    user: Principal;
    timestamp: _Time;
    details: string;
}): {
    id: string;
    status: SubmissionStatus;
    paymentMethod: PaymentMethod;
    user: Principal;
    timestamp: Time;
    details: string;
} {
    return {
        id: value.id,
        status: from_candid_SubmissionStatus_n17(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n19(_uploadFile, _downloadFile, value.paymentMethod),
        user: value.user,
        timestamp: value.timestamp,
        details: value.details
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    documentType: _DocumentType;
    user: Principal;
    fileName: string;
    fileSize: bigint;
    fileContent: _ExternalBlob;
    submissionId: string;
    uploadTime: _Time;
}): Promise<{
    id: string;
    documentType: DocumentType;
    user: Principal;
    fileName: string;
    fileSize: bigint;
    fileContent: ExternalBlob;
    submissionId: string;
    uploadTime: Time;
}> {
    return {
        id: value.id,
        documentType: from_candid_DocumentType_n27(_uploadFile, _downloadFile, value.documentType),
        user: value.user,
        fileName: value.fileName,
        fileSize: value.fileSize,
        fileContent: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.fileContent),
        submissionId: value.submissionId,
        uploadTime: value.uploadTime
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referenceType: _ReferenceType;
    submissionId: string;
    referenceValue: string;
}): {
    referenceType: ReferenceType;
    submissionId: string;
    referenceValue: string;
} {
    return {
        referenceType: from_candid_ReferenceType_n34(_uploadFile, _downloadFile, value.referenceType),
        submissionId: value.submissionId,
        referenceValue: value.referenceValue
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    completed: null;
} | {
    pendingPayment: null;
} | {
    processing: null;
} | {
    failed: null;
}): SubmissionStatus {
    return "paid" in value ? SubmissionStatus.paid : "completed" in value ? SubmissionStatus.completed : "pendingPayment" in value ? SubmissionStatus.pendingPayment : "processing" in value ? SubmissionStatus.processing : "failed" in value ? SubmissionStatus.failed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    card: null;
} | {
    cashapp: null;
} | {
    inPersonCash: null;
} | {
    paypal: null;
}): PaymentMethod {
    return "card" in value ? PaymentMethod.card : "cashapp" in value ? PaymentMethod.cashapp : "inPersonCash" in value ? PaymentMethod.inPersonCash : "paypal" in value ? PaymentMethod.paypal : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    affidavit: null;
} | {
    other: string;
} | {
    evidence: null;
} | {
    courtOrder: null;
}): {
    __kind__: "affidavit";
    affidavit: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "evidence";
    evidence: null;
} | {
    __kind__: "courtOrder";
    courtOrder: null;
} {
    return "affidavit" in value ? {
        __kind__: "affidavit",
        affidavit: value.affidavit
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "evidence" in value ? {
        __kind__: "evidence",
        evidence: value.evidence
    } : "courtOrder" in value ? {
        __kind__: "courtOrder",
        courtOrder: value.courtOrder
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paypalTransactionId: null;
} | {
    cashappUsername: null;
} | {
    storePaymentCode: null;
}): ReferenceType {
    return "paypalTransactionId" in value ? ReferenceType.paypalTransactionId : "cashappUsername" in value ? ReferenceType.cashappUsername : "storePaymentCode" in value ? ReferenceType.storePaymentCode : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n39(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CaseSubmission>): Array<CaseSubmission> {
    return value.map((x)=>from_candid_CaseSubmission_n15(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CaseDocument>): Promise<Array<CaseDocument>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CaseDocument_n25(_uploadFile, _downloadFile, x)));
}
function to_candid_DocumentType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NewCaseData_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewCaseData): _NewCaseData {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ReferenceType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReferenceType): _ReferenceType {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_SubmissionStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): _SubmissionStatus {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    details: string;
}): {
    paymentMethod: _PaymentMethod;
    details: string;
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n12(_uploadFile, _downloadFile, value.paymentMethod),
        details: value.details
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    card: null;
} | {
    cashapp: null;
} | {
    inPersonCash: null;
} | {
    paypal: null;
} {
    return value == PaymentMethod.card ? {
        card: null
    } : value == PaymentMethod.cashapp ? {
        cashapp: null
    } : value == PaymentMethod.inPersonCash ? {
        inPersonCash: null
    } : value == PaymentMethod.paypal ? {
        paypal: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReferenceType): {
    paypalTransactionId: null;
} | {
    cashappUsername: null;
} | {
    storePaymentCode: null;
} {
    return value == ReferenceType.paypalTransactionId ? {
        paypalTransactionId: null
    } : value == ReferenceType.cashappUsername ? {
        cashappUsername: null
    } : value == ReferenceType.storePaymentCode ? {
        storePaymentCode: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmissionStatus): {
    paid: null;
} | {
    completed: null;
} | {
    pendingPayment: null;
} | {
    processing: null;
} | {
    failed: null;
} {
    return value == SubmissionStatus.paid ? {
        paid: null
    } : value == SubmissionStatus.completed ? {
        completed: null
    } : value == SubmissionStatus.pendingPayment ? {
        pendingPayment: null
    } : value == SubmissionStatus.processing ? {
        processing: null
    } : value == SubmissionStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "affidavit";
    affidavit: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "evidence";
    evidence: null;
} | {
    __kind__: "courtOrder";
    courtOrder: null;
}): {
    affidavit: null;
} | {
    other: string;
} | {
    evidence: null;
} | {
    courtOrder: null;
} {
    return value.__kind__ === "affidavit" ? {
        affidavit: value.affidavit
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "evidence" ? {
        evidence: value.evidence
    } : value.__kind__ === "courtOrder" ? {
        courtOrder: value.courtOrder
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
